# Generated by Django 5.2.15 on 2026-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('best_selling_product', models.CharField(blank=True, max_length=200)),
                ('best_selling_qty', models.PositiveIntegerField(default=0)),
                ('payment_breakdown', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
