# Generated by Django 5.2.15 on 2026-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
